In [225]:
import nibabel as nib
import pandas as pd
import numpy as np

from nilearn import datasets
from pathlib import Path


In [226]:
def correct_mean_var(tseries):
    
# adapted from https://github.com/SIMEXP/niak/blob/master/commands/statistics/niak_correct_mean_var.m
# but for a 1D array
    
    nt = tseries.shape[0]
    tseries = tseries.reshape(nt,-1)
    
    mean_ts = np.mean(tseries,0)
    std_ts = tseries.std()
    
    tseries_n = (tseries - mean_ts)/std_ts
    tseries_n = np.ravel(tseries_n)
    
    return (tseries_n)

In [354]:
def build_size_roi(mask):
    
#adapted from https://github.com/SIMEXP/niak/blob/29260775b77d45af540c73705c88cdffa7bbcc39/commands/SI_processing/niak_build_size_roi.m

    nb_mask = len(mask)
    size_roi = np.zeros([nb_mask,1])

    labels_roi = np.unique(mask)
    labels_roi = labels_roi[labels_roi!=0]

    for num_r in range(nb_mask):
        size_roi[num_r] = np.count_nonzero(mask==labels_roi[num_r])
    
    #return (size_roi, labels_roi)
    return (size_roi)

In [ ]:
ts_path = Path("__file__").resolve().parents[1] / 'data' / 'test_tseries_python.csv'
conn_path = Path("__file__").resolve().parents[1] / 'data' / 'test_conn.csv'

In [ ]:
conn = pd.read_csv(conn_path, header=0)
conn = conn.values
conn[:,0] 

In [ ]:
tseries = pd.read_csv(ts_path, header=0)
tseries = tseries.values

In [ ]:
tseries_n = [correct_mean_var(ts) for ts in tseries.T]
tseries_n = np.array(tseries_n).T
tseries_n[:,1]

In [334]:
tseries_n.shape

(140, 64)

In [336]:
ir = tseries_n.var(axis=0)
ir

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [337]:
# load MIST 64 as mask

parcellations = datasets.fetch_atlas_basc_multiscale_2015(version='sym')
networks_64 = parcellations['scale064']

In [338]:
img = nib.load(networks_64)
a = np.array(img.dataobj)
a.shape

(53, 64, 52)

In [349]:
nb_mask = len(a[1])
nb_mask

64

In [350]:
all_mask = []

for num_m in range(1,1+nb_mask):
    array = np.array([num_m, 1])
    all_mask.append(array)

In [351]:
for num_m in range(nb_mask):
    all_mask[num_m] = a[:,num_m]

In [352]:
all_mask[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [355]:
N = build_size_roi(all_mask)
N 

array([[1033.],
       [ 420.],
       [ 360.],
       [ 805.],
       [ 517.],
       [ 747.],
       [ 404.],
       [ 285.],
       [ 753.],
       [ 372.],
       [ 977.],
       [1133.],
       [ 702.],
       [ 913.],
       [ 816.],
       [ 426.],
       [ 638.],
       [ 769.],
       [ 776.],
       [ 724.],
       [ 356.],
       [ 947.],
       [ 779.],
       [ 936.],
       [1072.],
       [ 725.],
       [1023.],
       [ 952.],
       [1132.],
       [ 685.],
       [ 656.],
       [ 751.],
       [ 377.],
       [ 644.],
       [1015.],
       [1013.],
       [ 868.],
       [ 722.],
       [ 777.],
       [ 951.],
       [1126.],
       [ 646.],
       [1052.],
       [ 940.],
       [1487.],
       [1749.],
       [1255.],
       [ 966.],
       [ 708.],
       [1105.],
       [1317.],
       [1173.],
       [1206.],
       [ 977.],
       [ 783.],
       [1026.],
       [1683.],
       [1039.],
       [1369.],
       [1319.],
       [1258.],
       [1032.],
       [

In [356]:
mask_0 = (N==0)|(N==1)
mask_0

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [357]:
N[mask_0] = 10
N[mask_0]

array([], dtype=float64)

In [358]:
ir = ((N*N)*ir-N)/(N*(N-1))
ir

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [174]:
with np.printoptions(threshold=np.inf):
    print(all_mask[4])

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 